CREATE TABLE IF NOT EXISTS alert_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Surrogate primary key.',
  event_id VARCHAR(128) NOT NULL UNIQUE COMMENT 'Stable upstream event id used for idempotency.',
  incident_id BIGINT NULL COMMENT 'Incident created or correlated from this alert event.',
  source VARCHAR(64) NOT NULL COMMENT 'Upstream source such as prometheus, apm, log-platform, or demo-payment-gateway.',
  signal_name VARCHAR(128) NOT NULL COMMENT 'Business or monitoring signal name.',
  service_name VARCHAR(128) NOT NULL COMMENT 'Affected service name.',
  endpoint VARCHAR(255) NULL COMMENT 'Affected endpoint, job, or business operation.',
  trace_id VARCHAR(128) NULL COMMENT 'Trace id or correlation id from the upstream event.',
  exception_type VARCHAR(128) NULL COMMENT 'Observed exception class or failure type.',
  summary TEXT NULL COMMENT 'Human-readable upstream alert summary.',
  error_rate DECIMAL(8, 4) NULL COMMENT 'Observed error rate carried by the alert event.',
  p95_latency INT NULL COMMENT 'Observed p95 latency in milliseconds.',
  qps INT NULL COMMENT 'Observed traffic rate.',
  affected_requests INT NULL COMMENT 'Affected request count in the alert window.',
  severity_hint VARCHAR(16) NULL COMMENT 'Upstream severity hint when available.',
  raw_payload_json JSON NULL COMMENT 'Original upstream alert payload.',
  status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED' COMMENT 'Ingest status: RECEIVED, IGNORED, INCIDENT_CREATED, CORRELATED.',
  decision_reason TEXT NULL COMMENT 'Why the event did or did not become an incident.',
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When the event entered Incident Copilot.',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row creation timestamp.',
  CONSTRAINT fk_alert_incident FOREIGN KEY (incident_id) REFERENCES incident(id),
  KEY idx_alert_incident (incident_id),
  KEY idx_alert_service_time (service_name, received_at),
  KEY idx_alert_trace_id (trace_id),
  KEY idx_alert_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Raw inbound alert/business events before incident correlation.';
