CREATE TABLE IF NOT EXISTS alert_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '代理主键。',
  event_id VARCHAR(128) NOT NULL UNIQUE COMMENT '上游稳定事件 ID，用于入站幂等。',
  incident_id BIGINT NULL COMMENT '该告警创建或关联的故障单。',
  source VARCHAR(64) NOT NULL COMMENT '上游来源，例如 prometheus、apm、log-platform 或 demo-payment-gateway。',
  signal_name VARCHAR(128) NOT NULL COMMENT '业务或监控信号名称。',
  service_name VARCHAR(128) NOT NULL COMMENT '受影响的服务名称。',
  endpoint VARCHAR(255) NULL COMMENT '受影响的端点、任务或业务操作。',
  trace_id VARCHAR(128) NULL COMMENT '上游链路追踪或关联 ID。',
  exception_type VARCHAR(128) NULL COMMENT '观察到的异常类型或失败类型。',
  summary TEXT NULL COMMENT '上游告警摘要。',
  error_rate DECIMAL(8, 4) NULL COMMENT '告警携带的观测错误率。',
  p95_latency INT NULL COMMENT '观测到的 p95 延迟（毫秒）。',
  qps INT NULL COMMENT '观测到的请求速率。',
  affected_requests INT NULL COMMENT '告警窗口内受影响请求数。',
  severity_hint VARCHAR(16) NULL COMMENT '上游严重等级提示。',
  raw_payload_json JSON NULL COMMENT '上游原始告警 payload。',
  status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED' COMMENT '入站状态：RECEIVED、IGNORED、INCIDENT_CREATED、CORRELATED。',
  decision_reason TEXT NULL COMMENT '该事件是否成为故障单的决策原因。',
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '告警进入系统时间。',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '行创建时间。',
  CONSTRAINT fk_alert_incident FOREIGN KEY (incident_id) REFERENCES incident(id),
  KEY idx_alert_incident (incident_id),
  KEY idx_alert_service_time (service_name, received_at),
  KEY idx_alert_trace_id (trace_id),
  KEY idx_alert_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='故障关联前的原始入站告警或业务事件。';
